name: Snake Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Run Snake Animation
        run: |
          git config --global user.name "Igordevz"
          git config --global user.email "programadorigor.dev@gmail.com"
          git clone https://github.com/Igordevz/github-contributions-snake-animation.git
          cd github-contributions-snake-animation
          python snake.py --username YourGitHubUsername --exclude weekends --grid

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Update contributions"
          git push origin main
